apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: blog-content
  namespace: flux-system
spec:
  image: ghcr.io/tomirgang/tomsblog/blog-content
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog-content
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog-content
  filterTags:
    pattern: '^sha-[a-f0-9]{7}$'
  policy:
    alphabetical:
      order: asc
