apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tomsblog
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/tomirgang/tomsblog
  ref:
    branch: main
  secretRef:
    name: tomsblog-git-credentials
