apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git-repository.yaml
  - kustomization-app.yaml
  - blog-content-image.yaml
  - blog-content-image-automation.yaml
  - user-management-image.yaml
  - user-management-image-automation.yaml
  - tenant-management-image.yaml
  - tenant-management-image-automation.yaml
