apiVersion: v1
kind: Secret
metadata:
    name: blog-content-secrets
    namespace: tomsblog
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:3IHg4vQbPBPZFGkoZgrNI9ZV5cDdqC4=,iv:AB5oc8HSHhHHWtlcgUIxn8kkU9QTPUNURptnrqkcTRI=,tag:0jTqKIrIbsNrxB5dNiFgag==,type:str]
# Database credentials (postgres-cluster-app) are automatically mirrored
# from the postgres namespace via Reflector (configured via inheritedMetadata
# in the CNPG Cluster spec).
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfxvv3ugp0cmtfgk0edlwq6xzdep28rzmk042x3j965jqsqlevnqfekm5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRjVweVFHcWtqQ2dqRy9X
            ZEkxQm1VZnlWSFBZN3F5VHcxeE9xOTNWU1VnCjJSWFhoSXBWUXlBRHdoeEYweVNp
            MVg5cXl1NXlKcTZsdkdWaDhya2kxcWMKLS0tIERSMEYybVVBMFF2bHFrTVhaTjR5
            djRseURxQ01iaDk3eElKMzdqSTFkZGsKuyiWW3W0USda5kVfJDK8V9sqrNtlyXI1
            oFGr4Ltagtr24tK72RtIduEPB/hIxX/LXDSq8VEURM4XiGx60qdSVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T12:57:28Z"
    mac: ENC[AES256_GCM,data:fqlACvJ+gZHuhiye7NyAVYMpn0bzKnZSpzQwBvF8BIrfaYcdJOn3mCjeUZMe2tHD09xBzL2DtGDjak0jH75g3+D98x6rYUOLxssA/elEHSiYjaSZnfiXA2eDMCfJ6pCohlRBA/M11DhmtzRLTtOE3qECF5hR6RIIND04E4dyLbU=,iv:C0ZniyDkDhKqMseLhIOh3zZVUietp6isMkPc0wWadwU=,tag:byId5f+sGxnDOoINAYlqJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
