apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: blog-content-http
  namespace: tomsblog
  labels:
    app: blog-content
spec:
  podSelector:
    matchLabels:
      app: blog-content
  port: http
  proxyProtocol: HTTP/1
