apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release-operator.yaml
  - cluster.yaml
  - topics.yaml
  - network-policy.yaml
