apiVersion: v1
kind: Secret
metadata:
    name: mongodb-password
    namespace: mongodb
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:xthil3dHL5chcJOclOx7G7z/TguKzsYhVTP9rST8h1AjSQq81/NMkUYtXew=,iv:EWaVCgAL6sdwNqIf28tykjI7an7Znw+hrPkZceTIYgM=,tag:3MbpTcnlBH9rtcKb1qpFXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfxvv3ugp0cmtfgk0edlwq6xzdep28rzmk042x3j965jqsqlevnqfekm5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdXhrMmUxZm9ZSGZSdFph
            bStlODFzRTdmMGErQ0FRVFlNRGlWUi9tOXpjCjR6S1RIWUJwTm9yV1BxYkxsa2Q2
            WGhJNlh3WVNVSzlHajdOdlUycjVXZHMKLS0tIG1KSlNPa2luMHhYdnMzRWhqVWc4
            MlBvdm8zdEtGTTV3R1RRNmtzSkFQY28KZP0ny3vwIfUrcXc0LjPPoYuWP/+hTRyj
            /ttD9ahCblDJjuD6ByZmnJITdRDtVUcpL0YGZ0kkohnWFKa/aUMOqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T18:59:42Z"
    mac: ENC[AES256_GCM,data:Kx3ywh3ywqzMxM0QR4GhcC9+yerWDcHo02sn/Z/vjIPK/BWJUaHYxRH7vDJAd/YYFKYoxLPlZvhoHc0R4Wf+t2Xm64Fuew9Fgklt9Shu7xAj1dyZHt5s/qA8NOKuJLwH3xMyDSwlHMedv/X91qgqkk8Z7Ie1qKlN5gNopya8TsU=,iv:45rqgx5GZ8ecO4Zf8lVd/24WqnjRusjMoA8Dukv1/fc=,tag:J/idOXJdPTEr/4GRnecmhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
