apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - traefik-namespace-patch.yaml
  - trust-anchor-issuer.yaml
  - trust-anchor-certificate.yaml
  - identity-issuer.yaml
  - helm-repository.yaml
  - helm-release-crds.yaml
  - helm-release-control-plane.yaml
