apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBrDCCAVOgAwIBAgIUTjlW37ynmzfkzXEFW7MRaLWENycwCgYIKoZIzj0EAwIw
    JTEjMCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjYwNTEx
    MDcxMTMyWhcNMzYwNTA4MDcxMTMyWjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQu
    Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCITFzSlO28x
    F0RWYLG7+EB9IG2ePuuWqtI+t2KuCuJ+AT3VPNQxJrbcuBwKJIM/ZXAVKFY7yCZO
    wZFusgUoJCqjYTBfMA4GA1UdDwEB/wQEAwIBBjAdBgNVHSUEFjAUBggrBgEFBQcD
    AQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUTQuRKPsxksmg
    JmqxPgProeSEKBgwCgYIKoZIzj0EAwIDRwAwRAIgC3gREmPhcGayjFIsULC+vbMY
    b35FeW6pe70exDf5uRUCIFiBjqnKqqxAwTqhq1y7+kZaAHY6c6oSutPu0z9XPJAw
    -----END CERTIFICATE-----
