apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBrTCCAVOgAwIBAgIUKiULe/VAp7mD67C8eno2zqAxBwswCgYIKoZIzj0EAwIw
    JTEjMCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjYwNTAy
    MTM1NDM1WhcNMzYwNDI5MTM1NDM1WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQu
    Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKi+Hs3/OJKS
    zOC2CmcLtpWVnnVVvCvyP61gUw7E8+muL1ojUkqH5CpNf/mxsbGD3mOkwZZt67LW
    tSk1MifgWuejYTBfMA4GA1UdDwEB/wQEAwIBBjAdBgNVHSUEFjAUBggrBgEFBQcD
    AQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU3EZfTABQA3P/
    0hApOqy8gG/FNkswCgYIKoZIzj0EAwIDSAAwRQIgXNZu7R/bSTxWxjV39cKByUct
    /c7hdvDvRUnoQu7EXOoCIQCdVLp99LAUhfYRIx4HZB1Tbw+7019VHx2H1eY/JDOz
    Lw==
    -----END CERTIFICATE-----
