site:
  title: 'Toms Blog: Dokumentation'
  start_page: tomsblog-arc42::index.adoc

content:
  sources:
    - url: .
      branches: [main, HEAD]
      tags: ['v*']
      start_path: docs/arc42
    - url: .
      branches: [main, HEAD]
      tags: ['v*']
      start_path: docs/design

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: partials/header-content.hbs
      contents: ./docs/supplemental-ui/partials/header-content.hbs

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - asciidoctor-kroki

runtime:
  fetch: true
