site:
  title: 'Toms Blog: Dokumentation'
  start_page: tomsblog-arc42::index.adoc

content:
  sources:
    - url: .
      branches: [main, HEAD]
      tags: ['v*']
      start_path: docs/arc42
    - url: .
      branches: [main, HEAD]
      tags: ['v*']
      start_path: docs/design
    - url: .
      branches: [main, HEAD]
      tags: ['v*', '!v0.1*', '!v0.2*', '!v0.3*', '!v0.4*', '!v0.5.0', '!v0.5.1', '!v0.5.2']
      start_path: docs/infra

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: partials/header-content.hbs
      contents: ./docs/supplemental-ui/partials/header-content.hbs

antora:
  extensions:
    - require: '@antora/lunr-extension'
      languages: [de, en]

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - asciidoctor-kroki

runtime:
  fetch: true
