apiVersion: v1
kind: Secret
metadata:
    name: user-management-secrets
    namespace: tomsblog
type: Opaque
stringData:
    service-api-key: ENC[AES256_GCM,data:vG07RDV+WHFbqarJek5dsF6K2R6fW0hcK8qtepIlodGShv1PBPHc9Y08LTA=,iv:XJN3juM2VgwCBLZwG9RqGS86EBrhdFKiR+ASCE8TwJw=,tag:5dZgxsHMSJcWbn1MpfpHVA==,type:str]
# Database credentials (postgres-cluster-app) are automatically mirrored
# from the postgres namespace via Reflector.
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfxvv3ugp0cmtfgk0edlwq6xzdep28rzmk042x3j965jqsqlevnqfekm5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUXA0MU1sZGd1L1JSSnYy
            SnpCck5GTDkxQzdjMnM2cFFIMDdqQWFtR25zCkE0eDVuNDYvTFNWdVpybEpndVkz
            bmhTUCtEa1ozY0VSQ012VGR0YlNmNU0KLS0tIEhjNElxMDlaTUxJSkx2cllxN3A3
            KytxS3RDbDZSWUJMRkhuY20vZ0tRL00KiBMcUZydCB0LNMaowm0KU0PRtPrUGRkr
            CzgztG2czvi3C05vz7G0DHfrbi7k1L/jFNRibn8C2gkmS9K41CPAeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T19:11:04Z"
    mac: ENC[AES256_GCM,data:BKuiHtvswVQLnB11a2kv63dIv/7/Ewb6BBRn3Zxd9MtgH25oWiK74lohlU4h2SrSHcPp6PBuS6tl9W99ANht/+o/nChuIeYM8NNwc4gRiFdxJ944a51VEDWdGpN/rIieQpWTD9zVs/474n6G9YyIDg4L2x/NC3Br0x9UBDoUTXE=,iv:KWABM5p7GSvbFgXkA05KWdHHUoMEz8//6fgS2Ynbp/I=,tag:Dhlr7W4E05Y+tHkWUb+Leg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
