apiVersion: v1
kind: Secret
metadata:
    name: user-management-secrets
    namespace: tomsblog
type: Opaque
stringData:
    service-api-key: ENC[AES256_GCM,data:vG07RDV+WHFbqarJek5dsF6K2R6fW0hcK8qtepIlodGShv1PBPHc9Y08LTA=,iv:XJN3juM2VgwCBLZwG9RqGS86EBrhdFKiR+ASCE8TwJw=,tag:5dZgxsHMSJcWbn1MpfpHVA==,type:str]
    admin-password: ENC[AES256_GCM,data:KunTu0AJ/0bhA5835md231xizjRBJ8w=,iv:uqfiJObNB5tmgtBrUQh3KjlckOYSVAMXCjF6qJXBY80=,tag:NyhCDRrZvV1gOIqPF3TxAg==,type:str]
# Database credentials (postgres-cluster-app) are automatically mirrored
# from the postgres namespace via Reflector (configured via inheritedMetadata
# in the CNPG Cluster spec).
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfxvv3ugp0cmtfgk0edlwq6xzdep28rzmk042x3j965jqsqlevnqfekm5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUXA0MU1sZGd1L1JSSnYy
            SnpCck5GTDkxQzdjMnM2cFFIMDdqQWFtR25zCkE0eDVuNDYvTFNWdVpybEpndVkz
            bmhTUCtEa1ozY0VSQ012VGR0YlNmNU0KLS0tIEhjNElxMDlaTUxJSkx2cllxN3A3
            KytxS3RDbDZSWUJMRkhuY20vZ0tRL00KiBMcUZydCB0LNMaowm0KU0PRtPrUGRkr
            CzgztG2czvi3C05vz7G0DHfrbi7k1L/jFNRibn8C2gkmS9K41CPAeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T04:39:36Z"
    mac: ENC[AES256_GCM,data:UA0NdgDSEuvz+AxUfmhZIt2u0RXEvxGAt/RJxXfEMxl4fkWQNT2gFWWUZZ4bp9uU3kXUaC2EuSLP36p5Y/P8/9gUwJk/p9F1L7AAAEaVJh84KTEvMC+ZKjle8Zjn7s8JxaBQ77Wtl4dx5hd0imtAg/xgPSvTh8U9Ws2QgYc1Kvo=,iv:oFV2EkLqRRASKOBTYJatssE5lRFT37SwHZNJvZePcIg=,tag:NylIZKITpbAzCjVM9wYm1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
