apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate-cluster-redirect.yaml
  - ingressroute-https-redirect.yaml
  - ingressroute-default-redirect.yaml
  - middleware-redirect-default-domain.yaml
