apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository-prometheus.yaml
  - helm-repository-grafana.yaml
  - secret.yaml
  - helm-release-kube-prometheus-stack.yaml
  - helm-release-loki.yaml
  - helm-release-promtail.yaml
  - helm-release-tempo.yaml
  - middleware-redirect-https.yaml
  - network-policy.yaml
