apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:G3BI73A=,iv:QiKsCC1HBx/XDKtOaED/0a3QPEik8OCaRvJ/jj1bAA4=,tag:sNrOao1u8MMtFnpfJcfAPw==,type:str]
    admin-password: ENC[AES256_GCM,data:Z75B+X7dWc2bxlM0KJ/J+Tlz/caqWTeGGzKVTk/N05Ds+/+3NxFpzWU+M/c=,iv:DqaZfQla1/PjUckF4+Nu1qlIkyjiJ9P1BgU6+5VLT/4=,tag:R4Q7yCLhfh9Y3miQVYHZaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfxvv3ugp0cmtfgk0edlwq6xzdep28rzmk042x3j965jqsqlevnqfekm5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRDhETEtaTms4WjBvRGtj
            a0tLb1RNMy96RnBldTVIakVxR1pUOVg4WEdnCnJGUldCT2dYTGZkaUdESU9JTDl1
            QW1DeWZmY2hSS3cxRDl4ekljeU1nMmcKLS0tIEVBYVo4ZGtRQzJGMjRhR0tEazlu
            L1RvR0h3bGJZUHA2dTRvTGkrNC80akUKVUTXrGgqYfj8OUYogmVEyt3zHQ6esGCX
            Wule6OTSm/8n75pdR2tstSoBkMMgXLqbfnPEOBgFl9bOu8GnP3j6Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T13:41:19Z"
    mac: ENC[AES256_GCM,data:Wa+K6qJA/l5T69H4M2WHnD/d/McN5neBtp33L2ruEyUBqh9iVLbgmbQPH2SJEld2siKzu5aDNn6LPy/PgjeXT0pjr1QX5dcDUPBjfvefTGu77hcXNsIL0f5iLmfBz+E1D74mTfaNl+aghe9G6Rz/lFuXrgJGryIkbrPxR7UXKiE=,iv:Defw8DN+g0isPJ+exvz8Ui8ix8nJz5L6/3fysL89qas=,tag:rUGe+2av3AcDbYJcSrgHGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
