apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - cert-manager
  - linkerd
  - postgres/namespace.yaml
  - postgres/backup-s3-credentials.yaml
  - postgres/cluster.yaml
  - postgres/databases.yaml
  - postgres/scheduled-backup.yaml
  - redis
  - pvc.yaml
  - blog-content
  - user-management
  - tenant-management
  - routing
