apiVersion: v1
kind: Secret
metadata:
  name: backup-s3-credentials
  namespace: postgres
type: Opaque
stringData:
  ACCESS_KEY_ID: "GKd8c50ab6a1583fb3f8db7bf2"
  SECRET_ACCESS_KEY: "07aa89e1ccff48388fa56ffb2eb403208c42912cd9c94e06c2e001edb21f7f53"
