apiVersion: v1
kind: Secret
metadata:
  name: backup-s3-credentials
  namespace: postgres
type: Opaque
stringData:
  ACCESS_KEY_ID: "GK1aaf91fef4c7fe7635794929"
  SECRET_ACCESS_KEY: "67b4f52719d715d3d3ce29b0a35f16b2976c43a2b7d1c5b259274d2affa94a9a"
