apiVersion: v1
kind: Secret
metadata:
    name: tenant-management-secrets
    namespace: tomsblog
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:cdOEcF5ia4YbCFelFhJudo/C8Kcq9Sk=,iv:JcKrRtCVnDMCuFOfhwhtuwz/04shjLfK33YuApy9TTI=,tag:zUFHnfpJPcNjTyo/j74IMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfxvv3ugp0cmtfgk0edlwq6xzdep28rzmk042x3j965jqsqlevnqfekm5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVGJzMTVuZVRKbExiK05x
            OENsbHBtaW8wL01IV3BhUWVMQ1IvMXd6YXowCmFnRWVKL2FDYmdEYUZzU2c0WWZq
            aW9BZ1RpUDFtdmRISWtKMzZxeEwyVE0KLS0tIGNLb0c0RjBDWVdXZ2RDbVkySjgx
            K3Jha3F3Q2lkQmVBV3k0dndMZ2huUlkKgnAEj5By+ZVLTNcb3ZpqazzfuM9eybTM
            IdxvpfEIQy299v62Byjpd5KxQx1PfhNNvcLvmOEbqXyf0Gth+M4MUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T07:54:05Z"
    mac: ENC[AES256_GCM,data:T3fbgqjuuXuG9kcmcTTk6bwE3A63pYls0+rC4Q89QY05IkFfXieIkokpjDvIoEbOC4VEuV35EsQuRYfPibL6f1WPL88lrjbzK84ST9i2JdFKmPeuaf5tblBn3Aw71wvzw99lwrQRZ/PRr/meDBTzDavQbJeGd4yQm98MOup9xSM=,iv:FRtBnVeUs9ZjZvfaKs268cr7ZOwhB5B89LiIzqo3GVc=,tag:W/7XqZO4lohUo9BgsO8tfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
