apiVersion: v1
kind: Secret
metadata:
    name: redis-password
    namespace: redis
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: tomsblog
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: tomsblog
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:XQx8WIrct338L18VQa91uB0Lwm89ypGnDxBoCVJz/CApJrFQy2/CQig9SFM=,iv:hV7bYwoNV1LuXHWp4TPSsWeiFihAmvVbnS2PqiKCpQE=,tag:wIdz1VNn00WEdEfXK/7NlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mfxvv3ugp0cmtfgk0edlwq6xzdep28rzmk042x3j965jqsqlevnqfekm5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY05uWFl5NzludU1rZjNM
            bFhmUzhuSUVQVVFYSUpieVdxVUVwcVdmRlFrCm9tTVpSK3RZRERONVRGdVpoMWFM
            NUE5UjF3RmpMcTcwR0pmWmx0eFhEVFEKLS0tIGo1Tm4wZHNqTSt5OG80ZEw2U1Iw
            SXdXM2tXQlFSQ0kwM2pnL3FLZUx3TUEKAxtjmyHRvWGMFZQC472bdJ1lmlAxmrcM
            ijGvCxUpqoJTHprBXSVVuJRg1VBvLhZsBCh625B6c8FkUuvzTzA6yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T06:12:35Z"
    mac: ENC[AES256_GCM,data:cZ6V3f0vNpvyLkdp8ivrCH6XHaXqWoLF5tFzycN5WbboCZgbKBrrn2AOxTTl7mjPs2pfqLwRfDQl472mq/uSmS32atosCm0lkhlBc1dpzwFso6NHpoeQDmSGMH/hFnWXYksw0pKsQH57pOPCghSRli///qzOesDHuM62JUfnf38=,iv:ZqxYwRqg44iW/A26JYyQonG87HjcsODiTSyXmJMPRBk=,tag:WYWygrvB6h9Ckmx8eSunMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
