site:
  title: 'Toms Blog: Dokumentation'
  start_page: tomsblog-arc42::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs/arc42
    - url: .
      branches: HEAD
      start_path: docs/design

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    kroki-server-url: http://localhost:8000
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki

runtime:
  fetch: true
