apiVersion: v1
kind: Service
metadata:
  name: feed
  namespace: tomsblog
  labels:
    app: feed
spec:
  type: ClusterIP
  selector:
    app: feed
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
